# The root logger with appender name 
log4j.rootLogger = debug, file
  
# Assign NAME a valid appender  
log4j.appender.file = org.apache.log4j.RollingFileAppender
log4j.appender.file.File=C:\\Users\\LENOVO\\eclipse-workspace\\com.Adaptix.Function\\src\\test\\resources\\logs\\Application.log
log4j.appender.file.maxFileSize=5000KB
log4j.appender.file.maxBackupIndex=1   
# Define the layout for NAME
log4j.appender.file.layout=org.apache.log4j.PatternLayout  
log4j.appender.file.layout.conversionPattern=%d{ABSOLUTE}%5p %C{1}:%L - %m%n 
#do not append the old file . Create a new log file everytime
log4j.appender.file.Append=false


#Application Logs
# Root Logger
log4j.logger.devpinoyLogger=DEBUG, dest1

# Direct log messages to stdout
log4j.appender.dest1=org.apache.log4j.RollingFileAppender
log4j.appender.dest1.maxFileSize=5000KB
log4j.appender.dest1.maxBackupIndex=3 
log4j.appender.dest1.layout=org.apache.log4j.PatternLayout
log4j.appender.dest1.layout.ConversionPattern=%d{yyyy-MM-dd HH:mm:ss}  %c %m%n
log4j.appender.dest1.File=C:\\Users\\LENOVO\\eclipse-workspace\\com.Adaptix.Function\\src\\test\\resources\\logs\\Application.log
#do not append the old file.create a new log file everytime
log4j.appender.dest1.Append=false
